name: sorteomovil
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^1.6.11
  sqflite: ^1.3.2+1
  state_persistence: ^0.0.7
  flutter_bloc: ^6.0.1
  intl: ^0.16.1
  awesome_dialog: ^1.2.1
  expansion_tile_card: ^1.1.0
  flutter_speed_dial: ^1.2.5
  rflutter_alert: ^1.1.0
  rxdart: ^0.23.1
  badges: ^1.1.4
  toggle_switch: ^0.1.8
  select_dialog: ^1.2.1
  url_launcher: ^5.5.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  shared_preferences: ^0.5.8
  progress_dialog: ^1.2.4
  uuid: 2.2.0
  auto_size_text: ^2.1.0
  share_files_and_screenshot_widgets: ^1.0.3
  excel: ^1.1.4
  esys_flutter_share: ^1.0.2
  xml: ^4.1.0
  font_awesome_flutter: ^8.10.0
  file_picker: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/shopping.png"
flutter_launcher_name:
  name: "CrazySales"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/arrow_up.gif

  fonts:
      - family: Roboto
        fonts:
          - asset: fonts/Roboto-Black.ttf
          - asset: fonts/Roboto-BlackItalic.ttf
          - asset: fonts/Roboto-Bold.ttf
          - asset: fonts/Roboto-BoldItalic.ttf
          - asset: fonts/Roboto-Italic.ttf
          - asset: fonts/Roboto-Light.ttf
          - asset: fonts/Roboto-LightItalic.ttf
          - asset: fonts/Roboto-Medium.ttf
          - asset: fonts/Roboto-MediumItalic.ttf
          - asset: fonts/Roboto-Regular.ttf
          - asset: fonts/Roboto-Thin.ttf
          - asset: fonts/Roboto-ThinItalic.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
